name: ci
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - '1.16'
          - '1.17'
          - '1.18'
          - '1.19'
          - '1.20'
          - '1.21'
          - '1.22'
          - '1.23'
          - '1.24'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Run go test
        run: |
          go vet ./...
          go build ./...
          go test ./... \
            -tags hasSed \
            -race -v \
            -coverprofile=cover.out -covermode atomic -coverpkg ./...
      - name: Upload coverage report
        uses: codecov/codecov-action@v5
        with:
          file: ./cover.out
  test-wasm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - '1.16' # supported oldest
          - '1.23' # oldstable
          - '1.24' # stable
    env:
      GOOS: js
      GOARCH: wasm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Get go_js_wasm_exec
        env:
          GO_BASE_URL: "https://raw.githubusercontent.com/golang/go/refs/heads/release-branch.go${{ matrix.go }}"
        run: |
          mkdir -p ${HOME}/.local/bin
          wget ${GO_BASE_URL}/lib/wasm/go_js_wasm_exec -O ${HOME}/.local/bin/go_js_wasm_exec \
            || wget ${GO_BASE_URL}/misc/wasm/go_js_wasm_exec -O ${HOME}/.local/bin/go_js_wasm_exec
          wget ${GO_BASE_URL}/lib/wasm/wasm_exec_node.js -O ${HOME}/.local/bin/wasm_exec_node.js \
            || wget ${GO_BASE_URL}/misc/wasm/wasm_exec.js -O ${HOME}/.local/bin/wasm_exec.js
          chmod +x ${HOME}/.local/bin/go_js_wasm_exec
      - name: Run go test
        run: |
          go vet ./...
          go build ./...
          go test ./... \
            -v \
            -exec=${HOME}/.local/bin/go_js_wasm_exec \
            -coverprofile=cover.out -covermode atomic -coverpkg ./...
      - name: Upload coverage report
        uses: codecov/codecov-action@v5
        with:
          file: ./cover.out
  tidy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.16'
      - name: Check tidied
        run: |
          go mod download
          go mod tidy
          git diff --exit-code go.mod go.sum
